# Site
name: "Deployed"
title: "Selfhost use Foss and drop Google"
description: "Selfhosted software to serve mobile devices"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://ippocratis.github.io'
google_analytics: 'G-53T8RWZ8BR'
disqus: 'ippocratis'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ippo:
    name: ippo
    display_name: ippo
    avatar: 'assets/images/avatar.png'
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    #description: "gggggg"
  sv1sjp:
    name: sv1sjp
    display_name: sv1sjp
    avatar: 'assets/images/50751574.jpeg'


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 100
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
